
export const ActionType = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE :"LOGIN_FAILURE",
    LOGIN_RESPONSE : "LOGIN_RESPONSE",
    GET_ME : "GET_ME",
    AVATAR_CHANGE : "AVATAR_CHANGE",
}
